# Generated by Django 5.2.1 on 2025-05-14 10:19

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=300, verbose_name='عنوان پروژه')),
                ('project_category', models.CharField(max_length=300, verbose_name='دسته بندی')),
                ('strat_date', models.DateField(blank=True, null=True, verbose_name='تاریخ شروع')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاریخ پایان')),
                ('customer', models.CharField(max_length=300, verbose_name='مشتری')),
                ('front_end', models.CharField(max_length=300, verbose_name='طراح')),
                ('image_1', models.ImageField(blank=True, null=True, upload_to='media', verbose_name='تصویر اول')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='media', verbose_name='تصویر دوم')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='media', verbose_name='تصویر سوم')),
                ('summary', models.CharField(max_length=500, verbose_name='خلاصه پروژه')),
            ],
            options={
                'verbose_name': 'پروژه',
                'verbose_name_plural': 'پروژه ها',
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='عنوان خدمت')),
                ('short_description', models.CharField(max_length=300, verbose_name='توضیحات کوتاه')),
                ('description', models.CharField(max_length=500, verbose_name='توضیحات')),
                ('service_image', models.ImageField(blank=True, null=True, upload_to='media', verbose_name='تصویر خدمت')),
            ],
            options={
                'verbose_name': 'خدمت',
                'verbose_name_plural': 'خدمات',
            },
        ),
        migrations.CreateModel(
            name='Work_Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wr_title', models.CharField(max_length=300, verbose_name='عنوان رزومه')),
                ('wr_company', models.CharField(max_length=300, verbose_name='شرکت')),
                ('wr_start_date', models.DateField(blank=True, null=True, verbose_name='تاریخ شروع به کار')),
                ('wr_end_date', models.DateField(blank=True, null=True, verbose_name='تاریخ پایان کار')),
                ('wr_task', models.CharField(max_length=300, verbose_name='وظایف و دستاوردها')),
            ],
            options={
                'verbose_name': 'سابقه کار',
                'verbose_name_plural': 'سوابق کاری',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='media', verbose_name='آوارتار')),
                ('work_time', models.IntegerField(verbose_name='سابقه کار به سال')),
                ('projects', models.IntegerField(verbose_name='تعداد پروژه های تکمیل شده')),
                ('description', models.CharField(max_length=500, verbose_name='توضیحات')),
                ('short_description', models.CharField(max_length=300, verbose_name='توضیحات کوتاه')),
                ('mobile_number', models.CharField(max_length=11, verbose_name='شماره تماس')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='تاریخ تولد')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربران',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
