# Generated by Django 5.2.1 on 2025-05-15 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personality', '0002_alter_user_projects_alter_user_work_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_main_setting',
            field=models.BooleanField(default=False, verbose_name='تنظیمات اصلی'),
        ),
    ]
