# Generated by Django 5.2.1 on 2025-05-15 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personality', '0003_user_is_main_setting'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='media', verbose_name='لوگو'),
        ),
    ]
