# Generated by Django 5.2.1 on 2025-05-17 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personality', '0004_user_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='media', verbose_name='فایل رزومه'),
        ),
    ]
