# Generated by Django 5.2.1 on 2025-05-20 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personality', '0005_user_resume'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=300, verbose_name='نام')),
                ('last_name', models.CharField(max_length=300, verbose_name='نام خانوادگی')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('mobile_number', models.CharField(verbose_name='شماره تماس')),
                ('message', models.CharField(max_length=500, verbose_name='متن پیام')),
                ('admin_message', models.TextField(blank=True, null=True, verbose_name='پاسخ ادمین')),
                ('is_read_admin', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد پیام')),
                ('services', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Service', to='personality.services', verbose_name='خدمت')),
            ],
            options={
                'verbose_name': 'تماس با ما',
                'verbose_name_plural': 'لیست ارتباط با ما',
            },
        ),
    ]
